# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run crawlers

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  python-tests:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v1.1.2
      id: cache-reqs
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ matrix.python-version }}-pip-${{ hashFiles('docs-crawler/requirements*.txt') }}
    - name: Install dependencies
      run:
        sudo apt-get update
        python -m pip install --upgrade pip
        hash -r
        pip install -r docs-crawler/requirements.txt
    - name: Run all crawlers
      run: |
        chmod +x docs-crawler/docs/run_crawlers.sh
        bash docs-crawler/docs/run_crawlers.sh
    - name: run aggregate_crawler
      run: python docs-crawler/docs/aggregate_crawler_output.py
        
