# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run crawlers

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install poetry
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.8.0
        poetry_version: 1.0
        working_directory: ./docs-crawlers # Optional, defaults to '.'
        args: install
      run: |
        cd docs-crawlers
        poetry install 
    - name: Run all crawlers
      run: |
        chmod +x docs-crawler/docs/run_crawlers.sh
        sh docs-crawler/docs/run_crawlers.sh
    - name: run aggregate_crawler
      run: python docs-crawler/docs/aggregate_crawler_output.py
        
